### ISSUE TITLE
Add option to extract sass library from this styleguide

### ISSUE THREAD

**Issue by daften** [StadGent/fractal_styleguide_gent-base#13]
What is in the scss folder and the public folder after grunt compile ATM. That should be an exportable/separate asset.

**Comment by daften** [comment]
Maybe use Travis to push to a separate repo? https://gist.github.com/willprice/e07efd73fb7f13f917ea

**Comment by daften** [comment]
Of met grunt builden en pushen: https://github.com/bower/bower/blob/master/Gruntfile.js

**Comment by meirege** [comment]
Commando `gulp publish --username=XXX --password=XXX --email=XXX` is ingebouwd. 
Dit gaat volgende folder structuur gaan publishen als NPM package:

CHANGELOG.md
LICENCE
README.md
build/
  sass/
  styleguide/
    fonts/
    img/
    js/
package.json

Deze kan dan in de starterkit ingeladen worden als npm package "gent_base".

**Comment by meirege** [comment]
@daften Momenteel gaat dit er ook voor zorgen dat het `gulp publish --username=XXX --password=XXX --email=XXX`commando publiekelijk te gebruiken zal zijn voor iedereen die deze repo gaat clonen.
Is dit een issue? 
Zolang de username en pass van digipolis niet gekend zijn is dat natuurlijk veilig. Maar in princiepe kan iedereen dan zijn eigen npm package gaan publishen van hieruit.

**Comment by daften** [comment]
@Jeroen005 Do we need the styleguide folder? And the build folder?
@meirege That's not an issue, everybody can do that anyway if they really want, that's the "downside" to open source.

**Comment by meirege** [comment]
We're going to put all assets inside a styleguide folder, so that when publishing to NPM we can just copy that folder to the "build" directory of the Drupal template when running gulp build in the Drupal starterkit theme.
The build folder is a folder used to combine the styleguide folder with all assets and the sass folder with all the SASS components.

**Comment by daften** [comment]
Mention in the correct PR that you're fixing this issue, so we have the links. For future reference, preferred option is  one PR per issue. You can always start a feature branch from another feature branch and rebase when necessary.
