### ISSUE TITLE
Support for Angular CLI

### ISSUE THREAD

**Issue by jdewilde** [StadGent/fractal_styleguide_gent-base#176]
The main.scss file uses import globbing statements, which is, by default, not supported for use with Angular CLI. Is it possible to create a main_cli.scss file with all the necassary references without globs?

## Environment

* Version used: 2.7.0
* Project: Digitale Front Office Inname Publieke ruimte

**Comment by meirege** [comment]
@jdewilde We bekijken dit issue deze middag voor jullie.

**Comment by jdewilde** [comment]
Top!

**Comment by meirege** [comment]
A main_cli.scss file has been added which imports all SASS partials without using SASS globbing.PR: https://github.com/StadGent/fractal_styleguide_gent-base/pull/177

@jdewilde Would this be a viable solution for your team?

**Comment by jdewilde** [comment]
This should solve my problem, I'll test the new configuration when available.

**Comment by jdewilde** [comment]
@meirege  I've update the package to 2.7.1 but where can I find the main_cli file?

**Comment by meirege** [comment]
@jdewilde I think something went wrong. I'll check it out for you.

**Comment by meirege** [comment]
@jdewilde We had an issue with a wrongly pushed tag (2.7.2) so we had to update to 2.7.3...

You should be good when updating to the 2.7.3 version of the gent_styleguide npm package. It should contain a components/main_cli.scss file with separate import statement per SASS partial.

**Comment by jdewilde** [comment]
@meirege I think there is still something missing.. message on 'npm install gent_styleguide'
touch: cannot touch 'components/main_cli.scss': No such file or directory
./postinstall.sh: line 37: components/main_cli.scss: No such file or directory

**Comment by meirege** [comment]
@jdewilde That seems to be a bug in the `postinstall.sh` script... 

However I have noticed if you do the install with `yarn install`, it does create the following folder:
`/node_modules/gent_styleguide/build/styleguide/sass` which contains the `main_cli.scss` file.

So as a temporary fix could you try it with Yarn instead of npm? 
That way you can test if the provided solution works until we've fixed this bug. 

We're sorry for the inconvenience!

**Comment by meirege** [comment]
@jdewilde Er is een nieuwe patch gepublished (2.7.4) die normaal jullie npm install issue zal verhelpen.
