### ISSUE TITLE
Keep mixins global or add to specific components?

### ISSUE THREAD

**Issue by meirege** [StadGent/fractal_styleguide_gent-base#20]
Should we keep the mixins in a global folder or add them to their component specific folders in Fractal?

**Comment by meirege** [comment]
After some consideration I would add all mixins inside a global directory. This makes it clear for all developers where new mixins should be placed and makes them reusable throughout the whole style guide.
@Jeroen005 @daften do you agree?

**Comment by daften** [comment]
Why not put the mixins within their components as much as possible? That should be part of the atomic design, shouldn't it? I'm not convinced a little easiness for devs should be the big selling point here.

**Comment by meirege** [comment]
I've moved some of the mixins to their component directories, some stayed in a global directory.

**Comment by daften** [comment]
Excellent
@meirege  Are the mix-ins that are global properly documented? SO it's clear why they are global ? :)

**Comment by meirege** [comment]
It should be obvious to any developer that mixins in that global directory like border-box(), clearfix() etc are there for a reason, because they get reused by multiple components and templates... but I could add more readme information to them so it's clear when you use Fractal. :)
